export type { ScraperInterface, ScraperConfig } from "./interfaces/scraper.interface";
export { BaseScraper } from "./interfaces/base-scraper";
export { ScraperRegistry } from "./registry/scraper-registry";
export { SearchService } from "./services/search.service";
export type { AggregatedSearchResult } from "./services/search.service";
export { CarrefourScraper } from "./carrefour/scraper";
export { CarrefourMapper } from "./carrefour/mapper";
export { CarrefourParser } from "./carrefour/parser";
export { AssaiScraper } from "./assai/scraper";
export { AssaiParser } from "./assai/parser";
export { AssaiMapper } from "./assai/mapper";
export { AssaiHealth } from "./assai/health";
export type { HealthCheckResult as AssaiHealthCheckResult } from "./assai/health";
export type { HealthCheckResult as AtacadaoHealthCheckResult } from "./atacadao/health";
export { AtacadaoScraper } from "./atacadao/scraper";
export { AtacadaoParser } from "./atacadao/parser";
export { AtacadaoMapper } from "./atacadao/mapper";
export { AtacadaoHealth } from "./atacadao/health";
export { PaoDeAcucarScraper } from "./paodeacucar/scraper";
