export type { ScraperInterface, ScraperConfig } from "./interfaces/scraper.interface";
export { BaseScraper } from "./interfaces/base-scraper";
export { ScraperRegistry } from "./registry/scraper-registry";
export { SearchService } from "./services/search.service";
export type { AggregatedSearchResult } from "./services/search.service";
export { CarrefourScraper } from "./carrefour/scraper";
export { AssaiScraper } from "./assai/scraper";
export { AtacadaoScraper } from "./atacadao/scraper";
export { PaoDeAcucarScraper } from "./paodeacucar/scraper";
export type { ScraperStrategy } from "./strategies/scraper-strategy";
export { VtexApiStrategy } from "./strategies/vtex-api-strategy";
export { NoopStrategy } from "./strategies/noop-strategy";
